# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-11-27 21:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0015_auto_20211127_2126'),
        ('past', '0005_enslavedcontribution_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptiveFate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptiveStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnslavedInRelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnslavementRelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('relation_type', models.IntegerField()),
                ('date', models.CharField(help_text='Date in MM,DD,YYYY format with optional fields.', max_length=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('text_ref', models.CharField(blank=True, help_text='Source text reference', max_length=255)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.Place')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.VoyageSources')),
                ('voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.Voyage')),
            ],
        ),
        migrations.CreateModel(
            name='EnslaverInRelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, help_text='The role of the enslaver in this relation', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='altethnicityname',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='language_group',
        ),
        migrations.RemoveField(
            model_name='enslaved',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='enslaved',
            name='is_adult',
        ),
        migrations.RemoveField(
            model_name='enslaved',
            name='modern_name_first',
        ),
        migrations.RemoveField(
            model_name='enslaved',
            name='modern_name_second',
        ),
        migrations.RemoveField(
            model_name='enslaved',
            name='modern_name_third',
        ),
        migrations.RemoveField(
            model_name='enslavedcontributionlanguageentry',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='languagegroup',
            name='modern_country',
        ),
        migrations.AddField(
            model_name='enslaved',
            name='dataset',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='last_known_date',
            field=models.CharField(blank=True, help_text='Date in format: MM,DD,YYYY', max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^(\\d{1,2}|),(\\d{1,2}|),(\\d{4}|)$', 32), code='invalid', message='Please type a date in the format MM,DD,YYYY (individual entries may be blank)')]),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='modern_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='notes',
            field=models.CharField(max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='skin_color',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enslaveralias',
            name='text_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='number_enslaved',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='text_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='number_enslaved',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='text_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moderncountry',
            name='languages',
            field=models.ManyToManyField(to='past.LanguageGroup'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='age',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='documented_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='gender',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='height',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, null=True, verbose_name='Height in inches'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='name_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='name_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='name_third',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='role',
            field=models.CharField(blank=True, help_text='The role of the enslaver in this relation', max_length=255),
        ),
        migrations.AlterField(
            model_name='languagegroup',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude of point'),
        ),
        migrations.AlterField(
            model_name='languagegroup',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude of point'),
        ),
        migrations.AlterField(
            model_name='moderncountry',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude of Country'),
        ),
        migrations.AlterField(
            model_name='moderncountry',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude of Country'),
        ),
        migrations.DeleteModel(
            name='AltEthnicityName',
        ),
        migrations.DeleteModel(
            name='Ethnicity',
        ),
        migrations.AddField(
            model_name='enslaverinrelation',
            name='enslaver_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='past.EnslaverAlias'),
        ),
        migrations.AddField(
            model_name='enslaverinrelation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslavers', to='past.EnslavementRelation'),
        ),
        migrations.AddField(
            model_name='enslavedinrelation',
            name='enslaved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='past.Enslaved'),
        ),
        migrations.AddField(
            model_name='enslavedinrelation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved', to='past.EnslavementRelation'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='captive_fate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.CaptiveFate'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='captive_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.CaptiveStatus'),
        ),
    ]
