# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-11-23 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0011_auto_20211116_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='enslaved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='past.Enslaved'),
        ),
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved', to='past.EnslavementRelation'),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslavers', to='past.EnslavementRelation'),
        ),
    ]
