# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-11-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0012_auto_20211123_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaveridentity',
            name='number_enslaved',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='number_enslaved',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='role',
            field=models.CharField(blank=True, help_text='The role of the enslaver in this relation', max_length=255),
        ),
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='role',
            field=models.CharField(blank=True, help_text='The role of the enslaver in this relation', max_length=255),
        ),
    ]
